### ISSUE TITLE
Realizar Banner de la tienda

### ISSUE THREAD

**Issue by JuanDCova** [CarsOk/tienda_ropa#11]
## Card
**Como** Usuario
**Quiero** Un Banner
**Para** Tener una mejor experiencia a la hora de visitar la pagina web

## Criterios de aceptación
- [ ] Calidad Superior a 1080p
- [ ] Colores relacionados al pedido del cliente 
- [ ] Tener una relacion de Aspecto 24:9

**Comment by JuanDCova** [comment]
# Imagenes Logo
*  ### Estas son las propuestas de logos y banner para nuestro proyecto.

![P1](https://user-images.githubusercontent.com/99416813/226070698-196f4e8a-bfa7-4454-9799-8fe010e3e88f.png)
![P2](https://user-images.githubusercontent.com/99416813/226070699-4fc9cccd-0756-4a17-a185-6643038f6d97.png)
![P3](https://user-images.githubusercontent.com/99416813/226070701-d544f89e-9e98-4078-a5ad-fc1de8b0405d.png)
![P4](https://user-images.githubusercontent.com/99416813/226070702-820311f9-ca68-4489-be82-98b54b8aa7f1.png)
![P5](https://user-images.githubusercontent.com/99416813/226070703-9ba71524-c305-4d73-9611-10a618de6b50.png)

**Comment by Danny7w7** [comment]
Buenas noches Sr Juan David Salgado Cova.
Se ha realizado una pequeña modificación en el Issue ya que en la "Mini-Reunión" que tuvimos el día Lunes 13 de Marzo se llego a la conclusión que como el logo ya estaba finiquitado usted solo tenia que realizar el banner para el NavBar de la Pagina web ya que este proyecto no posee redes sociales(o no se incluiran).

**Comment by YesidMoBa** [comment]
Buenas noches señores.
Estoy de acuerdo con mi compañero @Danny7w7 , ya que el logo principal del proyecto está realizado, revisado y aceptado por todos los miembros del equipo, en el Issues #6  encontraras el link del logo.

**Comment by JuanDCova** [comment]
## Caballeros estos son prototipos.
### Estos prototipos están diseñados de manera que puedan ser utilizados en distintas areas los invito a leer el documento donde se puede ver claramente como es aplicado.
[MANUAL DE MARCA CULTIVAR.pdf](https://github.com/CarsOk/tienda_ropa/files/11013403/MANUAL.DE.MARCA.CULTIVAR.pdf)
