### ISSUE TITLE
Corrección de errores visuales en la interfaz

### ISSUE THREAD

**Issue by JuanDCova** [CarsOk/tienda_ropa#183]
**Yo como**: Usuario del sistema
**Quiero:** Que se realicen correcciones en la interfaz para solucionar errores visuales y mejorar la experiencia de uso.
**Para:** Garantizar una interfaz más amigable y funcional que facilite la navegación y el uso adecuado de la plataforma.

### Criterios de Aceptación:
- [x] El enlace "a href" en el adminMenu debe redirigir correctamente hacia la tienda cuando se hace clic.
- [x] El botón de búsqueda debe funcionar correctamente, mostrando los resultados correspondientes a la consulta realizada.
- [x] El elemento "MT" en la sección de hombres debe mostrarse correctamente sin errores visuales.
- [x] En la vista de compra de artículos, se debe agregar una funcionalidad para seleccionar la talla deseada y que esta información se refleje correctamente en el proceso de compra.
- [x] El diseño del adminMenu debe ser consistente en todas las secciones y mostrarse correctamente sin errores visuales.
- [ ] La inversión de colores debe aplicarse de manera adecuada, mejorando la legibilidad y manteniendo una estética coherente en la interfaz.

**Comment by YesidMoBa** [comment]
No se tomo en cuenta el criterio " La inversión de colores debe aplicarse de manera adecuada, mejorando la legibilidad y manteniendo una estética coherente en la interfaz." ya que al colocarlo no combinaban los colores, quedo atento a cualquier otra sugerencia de colores @Danny7w7  @JuanDCova
