### ISSUE TITLE
Agregar funcionalidad para listar los pedidos en la vista de pedidos.

### ISSUE THREAD

**Issue by Danny7w7** [CarsOk/tienda_ropa#198]
**Yo como:** Administrador.
**Quiero:** Ver todos los pedidos realizados por los clientes en la vista de pedidos
**Para:** Tener un registro completo y poder administrar los pedidos de los clientes de manera eficiente.

### Criterios de Aceptación:
- [x] Cuando accedo a la vista de pedidos, se muestran todos los pedidos realizados por los clientes.
- [x] Cada pedido debe mostrar la información relevante, como el número de pedido, la fecha y hora de realización, el cliente que lo hizo y el estado actual del pedido.
- [ ] Los pedidos deben estar ordenados de manera cronológica, mostrando primero los más recientes.
- [ ] Debe haber una opción para filtrar los pedidos por estado, permitiéndome ver solo los pedidos en estado pendiente, en proceso o completados.
- [ ] Al hacer clic en un pedido, se muestra una vista detallada con toda la información del pedido, incluyendo los productos solicitados, las cantidades, el costo total y los datos de envío.

**Comment by JuanDCova** [comment]
Los ultimos 3 criterios de aceptacion se omitiran en este issue ya que la implementacion de estos se pospondra.
