### ISSUE TITLE
Vista Diagramas

### ISSUE THREAD

**Issue by Danny7w7** [CarsOk/tienda_ropa#2]
## Card
**Como:** Aprendiz SENA
**Quiero:** Crear la interfaz de los diagramas del proyecto formativo
**Para:** Tener claro los aspectos fundamentales de nuestro proyecto y funcionalidades
## Criterios de aceptacion
- [x] Informacion detallada de cada diagrama 
- [x] Diagramas en Html 
- [x] Mostrar los diagramas en formato PNG o JPG

**Comment by YesidMoBa** [comment]
Cumplir con los requisitos requeridos, agregar las imágenes.
