### ISSUE TITLE
Cartas de acercamiento 

### ISSUE THREAD

**Issue by Danny7w7** [CarsOk/tienda_ropa#20]
## Card 
**Como** instructor
**Quiero** Cartas de acercamiento
**Para** Llevar el control de las reuniones con el cliente.♥

## Criterios de aceptación 
- [ ] Sin errores ortográficos
- [ ] Cartas en formato PDF
- [ ] Misma estructura en las cartas

**Comment by JuanDCova** [comment]
# Cartas

### Adjunto evidencia de cartas de acercamiento, Reunión.

[Carta #1.pdf](https://github.com/CarsOk/tienda_ropa/files/11013258/Carta.1.pdf)
[Carta #2.pdf](https://github.com/CarsOk/tienda_ropa/files/11013257/Carta.2.pdf)
