### ISSUE TITLE
Documentacion del proyecto 

### ISSUE THREAD

**Issue by YesidMoBa** [CarsOk/tienda_ropa#7]
## Card
**Como:** Aprendiz SENA
**Quiero:** Toda la documentación del proyecto 
**Para:**  proveer de información útil y esencial a todos los integrantes 
## Criterios de aceptacion
- [ ] Formato PDF
- [ ] Todo organizado en una carpeta
- [ ] Nombre concreto del archivo agregado

**Comment by JuanDCova** [comment]
##Issues 7 cerrado
###### Se creo una carpeta donde se almaceno la documentacion de el proyecto formativo.
